### ISSUE TITLE
Returning in changing order

### ISSUE THREAD

**Issue by hedgehog1982** [NovatecConsulting/ca-apm-grafana-datasource#2]
Not sure if this a APM, the plugin or Grafana. Every time it auto refreshes the order of the metrics changes so the key and colours also change. Don't know if its worth sorting the Data before returning it so this doesnt happen?

**Comment by oberschlauberger** [comment]
Hi,
I'm struggling to reproduce this issue.

Are you referring to Grafana's auto-refresh feauture, e.g. "Refreshing every: 5s" in the time range menu or to some sort of browser reload?

Also, what browser and which versions of Grafana, CA APM and the data source are you using?

To my knowledge, Grafana's computation of the color palette is indeed based on the order of the series returned by the data source.

Anyway, I might implement some kind of sorting when I have some time to spare.

**Comment by oberschlauberger** [comment]
With commit 8448726a1e326e0e07b12b07c5a6694c0e829da5 the series are getting sorted alphabetically before being returned to Grafana.

Can you check whether your issue is still present when using this specific commit?

**Comment by hedgehog1982** [comment]
Morning, I've updated to the latest version of your plugin (but its still showing as 0.2 so may need to check). Still seeing issue. I'm on Chrome 70.  CA version is 10.5.2. 
I have a list of servers which I am monitoring CPU load they are called GH805, GH806, GH807, GH808, GH809, gh981, gh982, gh983, gh984, gh985, gh986. 
The order mostly stays correct but still moves around a bit in the series
![image](https://user-images.githubusercontent.com/26096809/49640765-49d14780-fa06-11e8-9112-4c3155b30cb6.png)
![image](https://user-images.githubusercontent.com/26096809/49640798-5eaddb00-fa06-11e8-9f19-d9646d5fe637.png)
I've attached the screenshots after the refresh

**Comment by oberschlauberger** [comment]
Hi again,

the v0.3.1 release does not contain the update - I implemented the sorting only in the specific commit I mentioned.

However, I guess I understand the your issue now. The latest release version (v0.4) now contains the sorting update and this time I also didn't forget to update the version number.

Please try again with v0.4 and let me know in case the issue persists.

**Comment by hedgehog1982** [comment]
Issue has been fixed. Thanks
