### ISSUE TITLE
Extract series labels from metric regex

### ISSUE THREAD

**Issue by AlexanderWert** [NovatecConsulting/ca-apm-grafana-datasource#4]
To provide more sophisticated series names, it would be very helpful, if series names could be extracted from the metric regex using capturing groups.

**Comment by oberschlauberger** [comment]
This feature will come with the next release. I hope to be done with this by the end of next week.

**Comment by oberschlauberger** [comment]
Implemented with 1713497756abd514985572d172815fbf9bb707b4 / release v0.4.1
