### ISSUE TITLE
Panel returns 500 internal server error

### ISSUE THREAD

**Issue by matiasba** [NovatecConsulting/ca-apm-grafana-datasource#7]
I have a panel with 11 querys that works fairly well but every few minutes it returns a 500 internal server error. The grafana log files only says:
t=2020-04-06T14:31:49-0300 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/1/introscope-web-services/services/MetricsDataService status=500 remote_addr=172.27.1.183 time_ms=574 size=504 referer="http://**.***.*.***:3000/d/JVgCECrZk/*****?orgId=1&refresh=1m"

And the error description on the panels gives this:

Object
status:500
statusText:"Internal Server Error"
data:Object
error:"Internal Server Error"
response:"<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><soapenv:Fault><faultcode>soapenv:Server.userException</faultcode><faultstring>java.util.ConcurrentModificationException</faultstring><detail><ns1:hostname xmlns:ns1="http://xml.apache.org/axis/">PWINMOM</ns1:hostname></detail></soapenv:Fault></soapenv:Body></soapenv:Envelope>"
message:"Internal Server Error"
message:"Internal Server Error"

**Comment by matiasba** [comment]
It may be related to the patch notes of the CA APM Connector 3.6.4
https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-enterprise-software/it-operations-management/service-operations-insight-connectors/connectors/ca-application-performance-management-connector-4-0-0/release-notes-for-ca-apm-connector-3-6-4.html

>###  APM Connector resets with java.util.ConcurrentModificationException
> When one connector on a server encounters java.util.ConcurrentModificationException,
>  the whole server and all running connectors on that server are affected. Due to this defect, the monitoring of monitoring software is affected.

Is there any way to catch this error and retry the query ? I may not be able to patch the APM Connector for sometime

**Comment by oberschlauberger** [comment]
Hi,
the error behavior you describe is a product bug related to the old Apache Axis version used by CA APM 10.7. The behavior occurs when there are many parallel requests to the APM web services. To my knowledge, the vendor is aware of this issue and I expect them to release a HotFix soon.

I thought about implementing a retry mechanism, but now I'm confident Broadcom/CA will solve this properly on the server side. I will update this issue once the corresponding HotFix is available.

**Comment by matiasba** [comment]
Is there any news on this topic? I cant find anything on a hotfix for this. Maybe you could reconsider a retry mechanism?

**Comment by oberschlauberger** [comment]
As far as I know, the official hotfix release has been delayed. I suggest you contact Broadcom/CA support and mention your issue to get a test hotfix.

I don't have the time to implement a retry mechanism and in our environments we use a test hotfix, so the issue is solved for us for the time being.

**Comment by oberschlauberger** [comment]
I just got word that APM 10.7 HF61 is now available through Broadcom support. The hotfix addresses the HTTP 500 error codes.

**Comment by matiasba** [comment]
Thanks for the news, I'm closing this issue.
