### ISSUE TITLE
CORS error with current Grafana ?

### ISSUE THREAD

**Issue by cmilazzo** [NovatecConsulting/ca-apm-grafana-datasource#9]
not really an issue with the data source i guess.     I am seeing the following error on the newest release of grafana.  v7.0.3 (00ee734baf).  Any guidance would be great.   Maybe I can use an older release? I am using the (server) source of course

Access to fetch at 'http://emhostname:8081/introscope-web-services;jsessionid=node01vuf7sai5ieo51l9miiaxnjwy869394.node0' (redirected from 'http://grafanahostname:3000/api/datasources/proxy/9/introscope-web-services/services/MetricsDataService?wsdl') from origin 'http://grafanahostname:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by oberschlauberger** [comment]
Hi,
- Does it work for you with previous Grafana versions?
- What is your exact CA APM version?
- Do you have any options checked in the data source auth settings other than "Basic auth"?

I have seen similar CORS issues only when using browser mode, so this is quite interesting. I did a quick test with Grafana v7.0.1 some days ago and did not experience such issues (server mode).

**Comment by cmilazzo** [comment]
First time I tried it
10.7 HF25
No  its not ssl  and i have basic credentials entered

**Comment by cmilazzo** [comment]
So I installed grafana 6.7.4 on another server and got the same result.   This leads me to believe that the issue is  my environment is some way.   I am using json datasource, graphite and prometheus with no issues.   All these datasources are making calls to similar servers in the same general subnets. 
Also a curl to the apmserver:8081 has not problem

**Comment by cmilazzo** [comment]
ok i tried another APM instance and it was fine.  The environment that i was trying is return all types of weird 303 status codes and nonsense.  I think there is problem with that environment specifically

ty for your help
